# NumPy 한번에 제대로 배우기



---



## NumPy 특징

* Numerical Python의 약자
* 고성능 과학 계산용 패키지로 강력한 N차원 배열 객체
* 범용적 데이터 처리에 사용 가능한 다차원 컨테이너
* 정교한 브로드캐스팅(broadcasting) 기능
* 파이썬의 자료형 list와 비슷하지만, 더 빠르고 메모리를 효율적으로 관리
* 반복문 없이 데이터 배열에 대한 처리를 지원하여 빠르고 편리
* 데이터 과학 도구에 대한 생태계의 핵심을 이루고 있음

In [2]:
import numpy as np



---



## 배열 생성

### 리스트로 배열 만들기


In [3]:
a1 = np.array([1,2,3,4,5])
print(a1)
print(type(a1))
print(a1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
print(a1[0],a1[1],a1[2],a1[3],a1[4])

1 2 3 4 5


In [6]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2)
print(a2.shape)
print(a2[0,0],a2[1,1],a2[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 5 9


### 배열 생성 및 초기화

* `zeros()`: 모든 요소를 0으로 초기화

In [11]:
np.zeros([2,2,2])

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

* `ones()`: 모든 요소를 1로 초기화

In [13]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

* `full()`: 모든 요소를 지정한 값으로 초기화

In [18]:
np.full([2,2],5)

array([[5, 5],
       [5, 5]])

* `eye()`: 단위행렬(identity matrix) 생성
  + 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

* `tri()`: 삼각행렬 생성

In [23]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

* `empty()`: 초기화되지 않은 배열 생성
  + 초기화가 없어서 배열 생성비용 저렴하고 빠름
  + 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음

In [24]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

* `_like()`: 지정된 배열과 shape가 같은 행렬 생성
  + `np.zeros_like()`
  + `np.ones_like()`
  + `np.full_like()`
  + `np.empty_like()`

In [25]:
print(a1)
np.zeros_like(a1)

[1 2 3 4 5]


array([0, 0, 0, 0, 0])

In [27]:
print(a2)
np.full_like(a2,10)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

### 생성한 값으로 배열 생성

* `arange()`: 정수 범위로 배열 생성

In [29]:
np.arange(0,30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

* `linspace()`: 범위 내에서 균등 간격의 배열 생성

In [31]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

* `logspace()`: 범위 내에서 균등간격으로 로그 스케일로 배열 생성

In [32]:
np.logspace(0,1,5)

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

### 랜덤값으로 배열 생성


* `random.random()`: 랜덤한 수의 배열 생성

In [34]:
np.random.random((3,3))

array([[0.31226756, 0.47121339, 0.13498123],
       [0.86615326, 0.93982117, 0.03696954],
       [0.93136538, 0.73083534, 0.16224117]])

* `random.randint()`: 일정 구간의 랜덤 정수의 배열 생성

In [35]:
np.random.randint((3,3))

array([0, 0])

In [41]:
import random as rand
rand.randint(1,5)

2

* `random.normal()`: 정규분포(normal distribution)를 고려한 랜덤한 수의 배열 생성
* 평균=0, 표준편차=1, 3 x 3 배열

In [42]:
np.random.normal(0,1,(3,3))

array([[ 1.30050526, -0.6634414 , -0.14369325],
       [ 0.94656478, -0.83063927, -1.01097115],
       [-1.30886774,  0.07442753,  0.75137266]])

* `random.rand()`: 균등분포(uniform distribution)를 고려한 랜덤한 수의 배열 생성

In [44]:
np.random.rand(3,3)

array([[0.66041797, 0.20017501, 0.65042644],
       [0.07037351, 0.12877238, 0.37069966],
       [0.26981752, 0.94075473, 0.184477  ]])

* `random.randn()`: 표준 정규 분포(standard normal distribution)를 고려한 랜덤한 수의 배열 생성

In [45]:
np.random.randn(3,3)

array([[-1.27009648, -0.89226607, -0.88575223],
       [-1.0487632 ,  0.31860643,  0.14495695],
       [-0.62677042, -0.63582082, -2.01788963]])

### 표준 데이터 타입

In [46]:
np.zeros(20,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [47]:
np.ones(20,dtype = bool)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [49]:
np.full((3,3),3,dtype = float)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

### 날짜/시간 배열 생성


In [50]:
date = np.array('2020-01-01',dtype = np.datetime64)
date 

array('2020-01-01', dtype='datetime64[D]')

In [52]:
date + np.arange(12)

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [54]:
datetime = np.datetime64('2020-06-01 12:00')
datetime

numpy.datetime64('2020-06-01T12:00')

In [55]:
datetime = np.datetime64('2020-06-01 12:00:12.34','ns')
datetime

numpy.datetime64('2020-06-01T12:00:12.340000000')



---



## 배열 조회

### 배열 속성 정보

In [60]:
def array_info(array):
    print(array)
    print("ndim:",array.ndim)
    print('shape:',array.shape)
    print("dtype:",array.dtype)
    print('size:',array.size)
    print('itemsize:',array.itemsize)
    print('nbytes:',array.nbytes)
    print('strides:',array.strides)

In [61]:
array_info(a1)

[1 2 3 4 5]
ndim: 1
shape: (5,)
dtype: int32
size: 5
itemsize: 4
nbytes: 20
strides: (4,)


In [62]:
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim: 2
shape: (3, 3)
dtype: int32
size: 9
itemsize: 4
nbytes: 36
strides: (12, 4)


### 인덱싱(Indexing)

In [63]:
print(a1)
print(a1[0])

[1 2 3 4 5]
1


In [66]:
print(a2)
print(a2[0,0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1


### 슬라이싱(Slicing)

* 슬라이싱 구문: `a[start:stop:step]`
* 기본값: start=0, stop=ndim, step=1

In [67]:
print(a1)
print(a1[0:2])
print(a1[0:])
print(a1[::2])

[1 2 3 4 5]
[1 2]
[1 2 3 4 5]
[1 3 5]


### 불리언 인덱싱(Boolean Indexing)

* 배열 각 요소의 선택 여부를 불리언(True or False)로 지정
* True 값인 인덱스의 값만 조회

In [69]:
print(a1)
b1 = [False,True,True,False,True]
print(b1)
print(a1[b1])

[1 2 3 4 5]
[False, True, True, False, True]
[2 3 5]


In [72]:
print(a2)
bi = np.random.randint(0,2,(3,3),dtype=bool)
print(bi)
print(a2[bi])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ True False  True]
 [ True False  True]
 [ True  True  True]]
[1 3 4 6 7 8 9]


### 팬시 인덱싱(Fancy Indedxing)

In [75]:
print(a1)
print(a1[0],a1[2])
ind = [0,2]
print(a1[ind])
ind  = np.array([[0,1],[2,0]])
print(a1[ind])

[1 2 3 4 5]
1 3
[1 3]
[[1 2]
 [3 1]]


In [78]:
print(a2)
row = np.array([0,2])
col = np.array([1,2])
print(a2[row,col])
print(a2[row,:])
print(a2[:,col])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]
[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]




---



## 배열 값 삽입/수정/삭제/복사

### 배열 값 삽입

* `insert()`: 배열의 특정 위치에 값 삽입
* axis를 지정하지 않으면 1차원 배열로 변환
* 추가할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [85]:
b1 = np.insert(a1,0,10)
c1 = np.insert(a1,2,20)
print(a1)
print(b1)
print(c1)

[1 2 3 4 5]
[10  1  2  3  4  5]
[ 1  2 20  3  4  5]


In [89]:
print(a2)
print()
b2 = np.insert(a2,1,10,axis = 0)
c2 = np.insert(a2,1,10,axis = 1)
print(b2)
print()
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]

[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


### 배열 값 수정

* 배열의 인덱싱으로 접근하여 값 수정

### 배열 값 삭제

* `delete()`: 배열의 특정 위치에 값 삭제
* axis를 지정하지 않으면 1차원 배열로 변환
* 삭제할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [90]:
print(a1)
a1[0] = 1
a1[1] = 2
a1[2] = 3
print(a1)
a1[:1] = 9
print(a1)

[1 2 3 4 5]
[1 2 3 4 5]
[9 2 3 4 5]


In [91]:
print(a2)
a2[0,0] = 1
a2[1,1] = 2
a2[2,2] = 3
a2[0] = 1
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 1 1]
 [4 2 6]
 [7 8 3]]


### 배열 복사

* 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님

In [96]:
print(a2,'\n')

print(a2[:2,:2],'\n')

a2_sub = a2[:2,:2]
print(a2_sub,'\n')

a2_sub[:,1] = 0
print(a2_sub,'\n')

print(a2)

[[1 0 1]
 [4 0 6]
 [7 8 3]] 

[[1 0]
 [4 0]] 

[[1 0]
 [4 0]] 

[[1 0]
 [4 0]] 

[[1 0 1]
 [4 0 6]
 [7 8 3]]



* `copy()`: 배열이나 하위 배열 내의 값을 명시적으로 복사

In [99]:
print(a2,'\n')
a2_sub_copy = a2[:2,:2].copy()
print(a2_sub_copy,'\n')
a2_sub_copy[:,1] = 1
print(a2,'\n')

[[1 0 1]
 [4 0 6]
 [7 8 3]] 

[[1 0]
 [4 0]] 

[[1 0 1]
 [4 0 6]
 [7 8 3]] 





---



## 배열 변환

### 배열 전치 및 축 변경

In [101]:
print(a2,'\n')
print(a2.T)

[[1 0 1]
 [4 0 6]
 [7 8 3]] 

[[1 4 7]
 [0 0 8]
 [1 6 3]]


In [103]:
print(a2)
print(a2.swapaxes(1,0))

[[1 0 1]
 [4 0 6]
 [7 8 3]]
[[1 4 7]
 [0 0 8]
 [1 6 3]]


### 배열 재구조화


* `reshape()`: 배열의 형상을 변경

In [104]:
n1= np.arange(1,10)
print(n1)
print(n1.reshape(3,3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


* `newaxis()`: 새로운 축 추가

In [106]:
print(n1)
print(n1[np.newaxis,:5])
print(n1[:5,np.newaxis])

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


### 배열 크기 변경

* 배열 모양만 변경

In [107]:
n2=  np.random.randint(0,10,(2,5))
print(n2)
n2.resize((5,2))
print(n2)

[[5 2 1 6 3]
 [4 5 3 1 1]]
[[5 2]
 [1 6]
 [3 4]
 [5 3]
 [1 1]]


* 배열 크기 증가
* 남은 공간은 0으로 채워짐

In [108]:
n2.resize((5,5))
print(n2)

[[5 2 1 6 3]
 [4 5 3 1 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


* 배열 크기 감소
* 포함되지 않은 값은 삭제됨

In [110]:
n2.resize((3,3))
print(n2)

[[5 2 1]
 [6 3 4]
 [5 3 1]]


### 배열 추가

* `append()`: 배열의 끝에 값 추가

In [111]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2 = np.arange(10,19).reshape(3,3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


* axis 지정이 없으면 1차원 배열 형태로 변형되어 결합

In [112]:
np.append(a2,b2)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

* axis를 0으로 지정
* shape[0]을 제외한 나머지 shape은 같아야 함

In [113]:
c2 = np.append(a2,b2,axis = 0)
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


* axis를 1로 지정
* shape[1]을 제외한 나머지 shape은 같아야 함

In [114]:
c2 = np.append(a2,b2,axis = 1)
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


### 배열 연결

* `concatenate()`: 튜플이나 배열의 리스트를 인수로 사용해 배열 연결

In [116]:
a1 = np.array([1,3,5])
b1 = np.array([2,4,6])
np.concatenate([a1,b1])

array([1, 3, 5, 2, 4, 6])

In [118]:
c1 = np.array([7,8,9])
np.concatenate([a1,b1,c1])

array([1, 3, 5, 2, 4, 6, 7, 8, 9])

In [120]:
a2 = np.array([[1,2,3],[4,5,6]])
np.concatenate([a2,a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [121]:
a2 = np.array([[1,2,3],[4,5,6]])
np.concatenate([a2,a2],axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* `vstack()`: 수직 스택(vertical stack), 1차원으로 연결

In [122]:
np.vstack([a2,a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

* `hstack()`: 수평 스택(horizontal stack), 2차원으로 연결

In [123]:
np.hstack([a2,a2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* `dstack()`: 깊이 스택(depth stack), 3차원으로 연결

In [124]:
np.dstack([a2,a2])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

* `stack()`: 새로운 차원으로 연결

In [126]:
np.stack([a2,a2])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

### 배열 분할

* `split()`: 배열 분할

In [128]:
a1 = np.arange(1,10)
print(a1)
b1,c1 = np.split(a1,[5])
print(b1,c1)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5] [6 7 8 9]


* `vsplit()`: 수직 분할, 1차원으로 분할

In [132]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2,c2 = np.vsplit(a2,[2])
print(b2,c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]] [[7 8 9]]


* `hsplit()`: 수평 분할, 2차원으로 분할

In [133]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2,c2 = np.hsplit(a2,[2])
print(b2,c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]] [[3]
 [6]
 [9]]


* `dsplit()`: 깊이 분할, 3차원으로 분할

In [134]:
a3 = np.arange(1,28).reshape(3,3,3)
print(a3)
b3,c3 = np.dsplit(a3,[2])
print(b3,c3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]

 [[19 20]
  [22 23]
  [25 26]]] [[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]

 [[21]
  [24]
  [27]]]




---



## 배열 연산

* NumPy의 배열 연산은 벡터화(vectorized) 연산을 사용
* 일반적으로 NumPy의 범용 함수(universal functions)를 통해 구현
* 배열 요소에 대한 반복적인 계산을 효율적으로 수행

### 브로드캐스팅(Broadcasting)

In [135]:
a1 = np.arange(1, 6)
print(a1)
print(a1 + 5)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [138]:
a1 = np.arange(1,4)
a2 = a1.reshape(3,1)
print(a1)
print(a2)
print(a1+a2)

[1 2 3]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


### 산술 연산(Arithmetic Operators)

In [147]:
a1 = np.arange(1, 10)
print(a1)
print(a1+1)
print(np.add(a1, 10))
print(a1 - 2)
print(np.subtract(a1, 10))
print(-a1)
print(a1 * 2)
print(np.multiply(a1, 2))
print(a1 / 2)
print(np.divide(a1, 2))
print(a1//2)
print(np.floor_divide(a1, 2))
print(a1 ** 2)
print(np.power(a1, 2))
print(a1 % 2)
print(np.mod(a1, 2))

[1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19]
[-1  0  1  2  3  4  5  6  7]
[-9 -8 -7 -6 -5 -4 -3 -2 -1]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[ 2  4  6  8 10 12 14 16 18]
[ 2  4  6  8 10 12 14 16 18]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0 1 1 2 2 3 3 4 4]
[0 1 1 2 2 3 3 4 4]
[ 1  4  9 16 25 36 49 64 81]
[ 1  4  9 16 25 36 49 64 81]
[1 0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0 1]


In [150]:
a1 = np.arange(1,10)
print(a1)
b1 = np.random.randint(1,10,size = 9)
print(b1)
print(a1+b1)
print(a1 * b1)
print( a1/ b1)
print(a1//b1)
print(a1**b1)
print(a1 % b1)

[1 2 3 4 5 6 7 8 9]
[1 1 5 8 3 4 1 2 2]
[ 2  3  8 12  8 10  8 10 11]
[ 1  2 15 32 15 24  7 16 18]
[1.         2.         0.6        0.5        1.66666667 1.5
 7.         4.         4.5       ]
[1 2 0 0 1 1 7 4 4]
[    1     2   243 65536   125  1296     7    64    81]
[0 0 3 4 2 2 0 0 1]


In [153]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2 = np.random.randint(1,10,size=(3,3))
print(b2)
print(a2+b2)
print(a2-b2)
print(a2/b2)
print(a2//b2)
print(a2**b2)
print(a2 % b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5 7 2]
 [7 7 7]
 [8 2 6]]
[[ 6  9  5]
 [11 12 13]
 [15 10 15]]
[[-4 -5  1]
 [-3 -2 -1]
 [-1  6  3]]
[[0.2        0.28571429 1.5       ]
 [0.57142857 0.71428571 0.85714286]
 [0.875      4.         1.5       ]]
[[0 0 1]
 [0 0 0]
 [0 4 1]]
[[      1     128       9]
 [  16384   78125  279936]
 [5764801      64  531441]]
[[1 2 1]
 [4 5 6]
 [7 0 3]]


#### 절대값 함수(Absolute Function)

* `absolute()`, `abs()`: 내장된 절대값 함수

In [155]:
a1 = np.random.randint(-10,10,size = 5)
print(a1)
print(np.absolute(a1))
print(np.abs(a1))

[-4 -4  3 -5  0]
[4 4 3 5 0]
[4 4 3 5 0]


#### 제곱/제곱근 함수

* `square`, `sqrt`: 제곱, 제곱근 함수

In [156]:
print(a1)
print(np.square(a1))
print(np.sqrt(a1))

[-4 -4  3 -5  0]
[16 16  9 25  0]
[       nan        nan 1.73205081        nan 0.        ]


<ipython-input-156-4e034cb7ea92>:3: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(a1))


#### 지수와 로그 함수 (Exponential and Log Function)

In [159]:
a1 = np.random.randint(1,10,size = 5)
print(a1)
print(np.exp(a1))
print(np.exp2(a1))
print(np.power(a1,2))

[7 2 7 9 3]
[1.09663316e+03 7.38905610e+00 1.09663316e+03 8.10308393e+03
 2.00855369e+01]
[128.   4. 128. 512.   8.]
[49  4 49 81  9]


In [160]:
print(a1)
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))

[7 2 7 9 3]
[1.94591015 0.69314718 1.94591015 2.19722458 1.09861229]
[2.80735492 1.         2.80735492 3.169925   1.5849625 ]
[0.84509804 0.30103    0.84509804 0.95424251 0.47712125]


#### 삼각 함수(Trigonometrical Function)


In [162]:
t = np.linspace(0,np.pi,3)
print(t)
print(np.sin(t))
print(np.cos(t))
print(np.tan(t))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [163]:
x = [-1,0,1]
print(x)
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))

[-1, 0, 1]
[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


### 집계 함수(Aggregate Functions)

#### sum(): 합 계산

In [165]:
a2 = np.random.randint(1,10,size=(3,3))
print(a2)
print(a2.sum(),np.sum(a2))
print(a2.sum(axis = 0),np.sum(a2,axis = 0 ))
print(a2.sum(axis = 1),np.sum(a2,axis = 1 ))

[[8 2 6]
 [2 4 7]
 [3 3 9]]
44 44
[13  9 22] [13  9 22]
[16 13 15] [16 13 15]


#### cumsum(): 누적합 계산

In [167]:
a2 = np.random.randint(1,10,size=(3,3))
print(a2)
print(np.cumsum(a2))
print(np.cumsum(a2,axis = 0 ))
print(np.cumsum(a2,axis = 1 ))

[[7 8 7]
 [3 1 7]
 [9 6 6]]
[ 7 15 22 25 26 33 42 48 54]
[[ 7  8  7]
 [10  9 14]
 [19 15 20]]
[[ 7 15 22]
 [ 3  4 11]
 [ 9 15 21]]


#### diff(): 차분 계산

In [168]:
a2 = np.random.randint(1,10,size=(3,3))
print(a2)
print(np.diff(a2))
print(np.diff(a2,axis = 0 ))
print(np.diff(a2,axis = 1 ))

[[7 5 8]
 [7 8 6]
 [4 7 4]]
[[-2  3]
 [ 1 -2]
 [ 3 -3]]
[[ 0  3 -2]
 [-3 -1 -2]]
[[-2  3]
 [ 1 -2]
 [ 3 -3]]


#### prod(): 곱 계산

In [170]:
a2 = np.random.randint(1,10,size=(3,3))
print(a2)
print(np.prod(a2))
print(np.prod(a2,axis = 0 ))
print(np.prod(a2,axis = 1 ))

[[1 9 5]
 [3 1 6]
 [1 3 3]]
7290
[ 3 27 90]
[45 18  9]


#### cumprod(): 누적곱 계산

In [171]:
a2 = np.random.randint(1,10,size=(3,3))
print(a2)
print(np.cumprod(a2))
print(np.cumprod(a2,axis = 0 ))
print(np.cumprod(a2,axis = 1 ))

[[8 8 9]
 [5 8 9]
 [2 5 5]]
[       8       64      576     2880    23040   207360   414720  2073600
 10368000]
[[  8   8   9]
 [ 40  64  81]
 [ 80 320 405]]
[[  8  64 576]
 [  5  40 360]
 [  2  10  50]]


#### dot()/matmul(): 점곱/행렬곱 계산

#### tensordot(): 텐서곱 계산

#### cross(): 벡터곱

#### inner()/outer(): 내적/외적

#### mean(): 평균 계산

#### std(): 표준 편차 계산

#### var(): 분산 계산

#### min(): 최소값

#### max(): 최대값

#### argmin(): 최소값 인덱스

#### argmax(): 최대값 인덱스

#### median(): 중앙값

#### percentile(): 백분위 수



#### any()

#### all()

### 비교 연산(Comparison Operators)


#### 불리언 연산자(Boolean Operators)


### 배열 정렬

#### 부분 정렬

* `partition()`: 배열에서 k개의 작은 값을 반환

## 배열 입출력


sample_data




---

